### ISSUE TITLE
Filter doesn't move to first page

### ISSUE THREAD

**Issue by gzai** [MedicOneSystems/livewire-datatables#339]
There is an issue with filtering when using pagination.

The filter work on first page. but after click page and select filter, datatable doesn't move to first page.

When I look at https://livewire-datatables.com/relation, after set filter on page 2, datatable move to first page.

How to solve this issue? 

![bug-filter-move-to-first-page](https://user-images.githubusercontent.com/4225733/141786013-0e4d4d14-f2c9-4a33-8d95-bd5af6bc20bb.gif)

```
class DatatableOfUsers extends LivewireDatatable
{

	public $exportable = true;

    public function builder()
    {
        return User::query();
    }

    public function columns()
    {
        return [
            NumberColumn::name('id')
                ->label('ID')
                ->defaultSort('asc')
                ->sortBy('id')
                ->hide(),

            Column::name('name')
                ->label('Name')
                ->searchable(),

            Column::name('email')
                ->label('Email')
                ->searchable(),

            Column::name('roles.name')
            	->filterOn('roles.name')
            	->filterable( $this->roles->pluck('name') )
            	->label('role'),

            DateColumn::name('created_at')
                ->label('Created at')
        ];
    }

    public function getRolesProperty()
    {
        return Role::all();
    }
}
```

**Comment by marionfromfrance** [comment]
Hi, it is solved in pull request here https://github.com/MedicOneSystems/livewire-datatables/pull/319

**Comment by gzai** [comment]
@marionfromfrance, after trying your commit, work like a charm. 
But why your PR still not merge with master.

Thanks marion

**Comment by marionfromfrance** [comment]
> @marionfromfrance, after trying your commit, work like a charm. But why your PR still not merge with master.
> 
> Thanks marion

You're welcome 🙂
